const formatPrice = (price) => {
  return price.toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
};
const agents = [
  {
    id: 1,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@realestate.in",
    phone: "+91-9876543210",
    address: "A-204, Prestige Towers, Bangalore - 560001",
    county: "Bangalore",
    town: "Bangalore",
    photo: "agent2.jpg",

    about:
      "Experienced real estate consultant with over 8 years in the Bangalore property market. Specializing in premium residential and commercial properties in IT corridors. Committed to finding the perfect property match for every client with personalized service and market expertise.",
    social: {
      facebook: "https://www.facebook.com/rajesh.kumar",
      instagram: "https://www.instagram.com/rajesh.realestate",
      twitter: "https://www.twitter.com/rajesh_properties",
      linkedin: "https://www.linkedin.com/in/rajesh-kumar-realestate",
    },
    featured: true,
    listings: [
      {
        id: 1,
        title: "Luxury 3BHK Apartment for Rent",
        slug: "luxury-3bhk-apartment-rent-koramangala",
        price: formatPrice(45000),
        location: "Bangalore",
        description:
          "Spacious 3BHK apartment in prime Koramangala location with modern amenities, covered parking, and 24/7 security. Features include modular kitchen, premium flooring, and excellent connectivity to IT parks.",
        images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Priya Sharma",
          image: "agent1.jpg",
        },
        features: {
          bedrooms: 3,
          status: true,
          garage: 1,
          elevator: true,
          kitchen: true,
        },
        address: {
          address: "Koramangala 5th Block",
          county: "Bangalore",
          city: "Bangalore",
          street: "80 Feet Road",
          area: "Koramangala",
        },

        featured: true,
        type: "rental",
        listedIn: "rentals",
        category: "Apartments",
      },
      {
        id: 2,
        title: "Premium Villa for Sale",
        slug: "premium-villa-sale-whitefield",
        price: formatPrice(8500000),
        location: "Bangalore",
        description:
          "Stunning 4BHK independent villa in Whitefield with landscaped garden, private parking, and premium interiors. Perfect for families seeking modern luxury living.",
        images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Rajesh Kumar",
          image: "agent3.jpg",
        },
        features: {
          bedrooms: 4,
          status: true,
          garage: 2,
          elevator: false,
          kitchen: true,
        },
        address: {
          address: "Whitefield Main Road",
          county: "Bangalore",
          city: "Bangalore",
          street: "ITPL Main Road",
          area: "Whitefield",
        },
        featured: true,
        type: "sale",
        listedIn: "Sales",
        category: "Houses",
      },
    ],
  },
  {
    id: 2,
    name: "Priya Sharma",
    email: "priya.sharma@realestate.in",
    phone: "+91-9845678901",
    address: "B-101, Brigade Gateway, Bangalore - 560026",
    county: "Bangalore",
    town: "Bangalore",
    about:
      "Dynamic property consultant specializing in luxury apartments and villas across Bangalore. With a client-first approach and deep understanding of the local market, I help families and professionals find their dream homes in prime locations.",
    social: {
      facebook: "https://www.facebook.com/priya.sharma",
      instagram: "https://www.instagram.com/priya_properties",
      twitter: "https://www.twitter.com/priya_realestate",
      linkedin: "https://www.linkedin.com/in/priya-sharma-realtor",
    },
    featured: true,
    photo: "agent4.jpg",
    listings: [
      {
        id: 1,
        title: "Luxury 3BHK Apartment for Rent",
        slug: "luxury-3bhk-apartment-rent-koramangala",
        price: formatPrice(45000),
        location: "Bangalore",
        description:
          "Spacious 3BHK apartment in prime Koramangala location with modern amenities, covered parking, and 24/7 security.",
        images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Priya Sharma",
          image: "agent1.jpg",
        },
        features: {
          bedrooms: 3,
          status: true,
          garage: 1,
          elevator: true,
          kitchen: true,
        },
        address: {
          address: "Koramangala 5th Block",
          county: "Bangalore",
          city: "Bangalore",
          street: "80 Feet Road",
          area: "Koramangala",
        },

        featured: true,
        type: "rental",
        listedIn: "rentals",
        category: "Apartments",
      },
      {
        id: 2,
        title: "Modern 2BHK Apartment in Bandra",
        slug: "modern-2bhk-apartment-bandra",
        price: formatPrice(65000),
        location: "Mumbai",
        description:
          "Contemporary 2BHK apartment in upscale Bandra West with sea-facing views, premium amenities, and close proximity to shopping and entertainment.",
        images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Priya Sharma",
          image: "agent3.jpg",
        },
        features: {
          bedrooms: 2,
          status: true,
          garage: 1,
          elevator: true,
          kitchen: true,
        },
        address: {
          address: "Bandra West",
          county: "Mumbai",
          city: "Mumbai",
          street: "Linking Road",
          area: "Bandra",
        },
        featured: true,
        type: "rental",
        listedIn: "rentals",
        category: "Apartments",
      },
    ],
  },
  {
    id: 3,
    name: "Amit Patel",
    email: "amit.patel@realestate.in",
    phone: "+91-9923456789",
    address: "C-305, DLF Cyber City, Gurgaon - 122002",
    county: "Gurgaon",
    town: "Gurgaon",
    about:
      "Premium property specialist focusing on high-end residential and commercial spaces in Delhi NCR. Known for exceptional negotiation skills and comprehensive market knowledge, helping clients make informed investment decisions.",
    social: {
      facebook: "https://www.facebook.com/amit.patel.realtor",
      instagram: "https://www.instagram.com/amit_properties",
      twitter: "https://www.twitter.com/amit_realestate",
      linkedin: "https://www.linkedin.com/in/amit-patel-property",
    },
    photo: "agent3.jpg",
    featured: true,
    listings: [
      {
        id: 1,
        title: "Renovated Penthouse for Sale",
        slug: "renovated-penthouse-sale-gurgaon",
        price: formatPrice(15000000),
        location: "Gurgaon",
        description:
          "Luxurious 5BHK penthouse in DLF Phase 5 with private terrace, modern European kitchen, imported fittings, and panoramic city views.",
        images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Amit Patel",
          image: "agent1.jpg",
        },
        features: {
          bedrooms: 5,
          status: true,
          garage: 3,
          elevator: true,
          kitchen: true,
        },
        address: {
          address: "DLF Phase 5",
          county: "Gurgaon",
          city: "Gurgaon",
          street: "Golf Course Road",
          area: "DLF Phase 5",
        },

        featured: true,
        type: "sale",
        listedIn: "Sales",
        category: "Houses",
      },
      {
        id: 2,
        title: "Commercial Office Space",
        slug: "commercial-office-hinjewadi",
        price: formatPrice(75000),
        location: "Pune",
        description:
          "Premium commercial office space in Hinjewadi IT Park Phase 1 with modern infrastructure and ample parking.",
        images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Amit Patel",
          image: "agent3.jpg",
        },
        features: {
          bedrooms: 0,
          status: true,
          garage: 10,
          elevator: true,
          kitchen: false,
        },
        address: {
          address: "Hinjewadi Phase 1",
          county: "Pune",
          city: "Pune",
          street: "Rajiv Gandhi Infotech Park",
          area: "Hinjewadi",
        },
        featured: true,
        type: "rental",
        listedIn: "rentals",
        category: "Offices",
      },
    ],
  },
  {
    id: 4,
    name: "Sneha Reddy",
    email: "sneha.reddy@realestate.in",
    phone: "+91-9912345678",
    address: "D-502, Cyber Towers, Hyderabad - 500081",
    county: "Hyderabad",
    town: "Hyderabad",
    about:
      "Dedicated real estate professional with expertise in Hyderabad's IT corridor properties. Passionate about connecting clients with properties that match their lifestyle and investment goals. Known for transparency and timely service delivery.",
    social: {
      facebook: "https://www.facebook.com/sneha.reddy.realtor",
      instagram: "https://www.instagram.com/sneha_properties",
      twitter: "https://www.twitter.com/sneha_realestate",
      linkedin: "https://www.linkedin.com/in/sneha-reddy-property",
    },
    photo: "agent3.jpg",
    featured: true,
    listings: [
      {
        id: 1,
        title: "Spacious 3BHK Apartment for Sale",
        slug: "spacious-3bhk-apartment-sale-hyderabad",
        price: formatPrice(6500000),
        location: "Hyderabad",
        description:
          "Well-designed 3BHK apartment in Gachibowli with vastu-compliant layout, children's play area, and swimming pool.",
        images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Sneha Reddy",
          image: "agent1.jpg",
        },
        features: {
          bedrooms: 3,
          status: true,
          garage: 1,
          elevator: true,
          kitchen: true,
        },
        address: {
          address: "Gachibowli",
          county: "Hyderabad",
          city: "Hyderabad",
          street: "Serilingampally",
          area: "Gachibowli",
        },

        featured: true,
        type: "sale",
        listedIn: "Sales",
        category: "Apartments",
      },
      {
        id: 2,
        title: "Elegant 4BHK Villa for Sale",
        slug: "elegant-4bhk-villa-sale-chennai",
        price: formatPrice(12000000),
        location: "Chennai",
        description:
          "Beautiful 4BHK villa in OMR with contemporary design, private garden, and premium fixtures. Features solar panels and eco-friendly construction.",
        images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
        amenities: [
          "Air Conditioning",
          "Security System",
          "Parking Space",
          "Gym Room",
          "Free WIFI",
          "Fire Place",
        ],
        agent: {
          name: "Sneha Reddy",
          image: "agent3.jpg",
        },
        features: {
          bedrooms: 4,
          status: true,
          garage: 2,
          elevator: false,
          kitchen: true,
        },
        address: {
          address: "Old Mahabalipuram Road",
          county: "Chennai",
          city: "Chennai",
          street: "OMR Perungudi",
          area: "OMR",
        },
        featured: true,
        type: "sale",
        listedIn: "Sales",
        category: "Houses",
      },
    ],
  },
];

export default agents;
