const formatPrice = (price) => {
  return price.toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
};

const listing = [
  {
    id: 1,
    title: "Luxury 3BHK Apartment for Rent",
    slug: "luxury-3bhk-apartment-rent-koramangala",
    price: formatPrice(45000),
    location: "Bangalore",
    description:
      "Spacious 3BHK apartment in prime Koramangala location with modern amenities, covered parking, and 24/7 security. Features include modular kitchen, premium flooring, and excellent connectivity to IT parks and metro stations.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Priya Sharma",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Koramangala 5th Block",
      county: "Bangalore",
      city: "Bangalore",
      street: "80 Feet Road",
      area: "Koramangala",
    },

    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Apartments",
  },
  {
    id: 2,
    title: "Premium Villa for Sale",
    slug: "premium-villa-sale-whitefield",
    price: formatPrice(8500000),
    location: "Bangalore",
    description:
      "Stunning 4BHK independent villa in Whitefield with landscaped garden, private parking, and premium interiors. Perfect for families seeking modern luxury living with excellent connectivity to tech parks and schools.",
    images: ["image8.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Rajesh Kumar",
      image: "agent3.jpg",
    },
    features: {
      bedrooms: 4,
      status: true,
      garage: 2,
      elevator: false,
      kitchen: true,
    },
    address: {
      address: "Whitefield Main Road",
      county: "Bangalore",
      city: "Bangalore",
      street: "ITPL Main Road",
      area: "Whitefield",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Houses",
  },
  {
    id: 3,
    title: "Modern 2BHK Apartment in Bandra",
    slug: "modern-2bhk-apartment-bandra",
    price: formatPrice(65000),
    location: "Mumbai",
    description:
      "Contemporary 2BHK apartment in upscale Bandra West with sea-facing views, premium amenities, and close proximity to shopping centers, restaurants, and entertainment hubs. Ideal for young professionals.",
    images: ["image7.jpg", "image3.jpg", "image2.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Sneha Reddy",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 2,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Bandra West",
      county: "Mumbai",
      city: "Mumbai",
      street: "Linking Road",
      area: "Bandra",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Apartments",
  },
  {
    id: 4,
    title: "Renovated Penthouse for Sale",
    slug: "renovated-penthouse-sale-gurgaon",
    price: formatPrice(15000000),
    location: "Gurgaon",
    description:
      "Luxurious 5BHK penthouse in DLF Phase 5 with private terrace, modern European kitchen, imported fittings, and panoramic city views. Features include home theater, wine cellar, and smart home automation.",
    images: ["image4.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Amit Patel",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 5,
      status: true,
      garage: 3,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "DLF Phase 5",
      county: "Gurgaon",
      city: "Gurgaon",
      street: "Golf Course Road",
      area: "DLF Phase 5",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Houses",
  },
  {
    id: 5,
    title: "Commercial Office Space in Hinjewadi",
    slug: "commercial-office-hinjewadi",
    price: formatPrice(75000),
    location: "Pune",
    description:
      "Premium commercial office space in Hinjewadi IT Park Phase 1 with modern infrastructure, ample parking, power backup, and excellent connectivity. Perfect for IT companies and startups looking for Grade A office space.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Arjun Singh",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 0,
      status: true,
      garage: 10,
      elevator: true,
      kitchen: false,
    },
    address: {
      address: "Hinjewadi Phase 1",
      county: "Pune",
      city: "Pune",
      street: "Rajiv Gandhi Infotech Park",
      area: "Hinjewadi",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Offices",
  },
  {
    id: 6,
    title: "Spacious 3BHK Apartment for Sale",
    slug: "spacious-3bhk-apartment-sale-hyderabad",
    price: formatPrice(6500000),
    location: "Hyderabad",
    description:
      "Well-designed 3BHK apartment in Gachibowli with vastu-compliant layout, children's play area, swimming pool, and clubhouse. Located in the heart of IT corridor with easy access to HITEC City and financial district.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Kavya Iyer",
      image: "agent2.jpg",
    },
    features: {
      bedrooms: 3,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Gachibowli",
      county: "Hyderabad",
      city: "Hyderabad",
      street: "Serilingampally",
      area: "Gachibowli",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Apartments",
  },
  {
    id: 7,
    title: "Boutique Retail Space for Rent",
    slug: "boutique-retail-space-rent-delhi",
    price: formatPrice(120000),
    location: "Delhi",
    description:
      "Prime retail space in Connaught Place with high footfall, excellent visibility, and modern amenities. Ideal for flagship stores, boutiques, or premium brands looking for presence in Delhi's commercial heart.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Vikram Malhotra",
      image: "agent1.jpg",
    },
    features: {
      bedrooms: 0,
      status: true,
      garage: 5,
      elevator: true,
      kitchen: false,
    },
    address: {
      address: "Connaught Place",
      county: "Delhi",
      city: "New Delhi",
      street: "Rajiv Chowk",
      area: "Connaught Place",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Retails",
  },
  {
    id: 8,
    title: "Cozy 2BHK Apartment for Rent",
    slug: "cozy-2bhk-apartment-rent-noida",
    price: formatPrice(25000),
    location: "Noida",
    description:
      "Comfortable 2BHK apartment in Sector 62 with modern amenities, covered parking, and power backup. Well-connected to Delhi via metro and close to shopping malls, hospitals, and schools. Perfect for small families.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Neha Kapoor",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 2,
      status: true,
      garage: 1,
      elevator: true,
      kitchen: true,
    },
    address: {
      address: "Sector 62",
      county: "Noida",
      city: "Noida",
      street: "Noida Expressway",
      area: "Sector 62",
    },
    featured: true,
    type: "rental",
    listedIn: "rentals",
    category: "Apartments",
  },
  {
    id: 9,
    title: "Elegant 4BHK Villa for Sale",
    slug: "elegant-4bhk-villa-sale-chennai",
    price: formatPrice(12000000),
    location: "Chennai",
    description:
      "Beautiful 4BHK villa in OMR with contemporary design, private garden, servant quarters, and premium fixtures. Features rainwater harvesting, solar panels, and eco-friendly construction. Close to IT corridor and schools.",
    images: ["image2.jpg", "image3.jpg", "image7.jpg", "image8.jpg"],
    amenities: [
      "Air Conditioning",
      "Security System",
      "Parking Space",
      "Gym Room",
      "Free WIFI",
      "Fire Place",
    ],
    agent: {
      name: "Suresh Krishnan",
      image: "agent4.jpg",
    },
    features: {
      bedrooms: 4,
      status: true,
      garage: 2,
      elevator: false,
      kitchen: true,
    },
    address: {
      address: "Old Mahabalipuram Road",
      county: "Chennai",
      city: "Chennai",
      street: "OMR Perungudi",
      area: "OMR",
    },
    featured: true,
    type: "sale",
    listedIn: "Sales",
    category: "Houses",
  },
];

export default listing;
